### ISSUE TITLE
1 PROJE ÖZETİ - English

### ISSUE THREAD

**Issue by ZekeriyaAY** [LoRaChain/Documents#2]

**Comment by ervacoban** [comment]
The LoRaChain project simply combines LoRa communication modules and blockchain technology to create a messaging platform without any servers. Just as regular messaging platforms, messages can be sent even if the receiver is offline without any third party requirement. Besides that, message transferring time must be kept low. By using the LoRa modules, any internet connection is not required. And by that, any problem that occurs with internet communication is automatically solved. In addition to serverless communication, there won’t be any risky system that stores these messages. With a strong encryption system and the blockchain technology, communication will be safe.

Key words: LoRaWan, LoRa, Communication, Chat, Chat Program, Blockchain, Go Ether
