### ISSUE TITLE
3a KONU

### ISSUE THREAD

**Issue by ZekeriyaAY** [LoRaChain/Documents#4]

**Comment by BlackHacherUU** [comment]
3 a KONU(Abdullah HASAN)
 Günümüzde Wİ-Fİ kullanmayan insan yoktur. Biz de server’e istek gönderip bilgiler alabiliriz. Bir server çöktüğünde istemciler (Clients) iletişim kuramıyor ve sıkıntı yaşıyor. Son günlerde sosyal medyada bazı uygulamalar bir süre çalışmaz haline geldiği için insanlar iletişim kuramıdalar. Böylece yeni uygulama indirip başka yol arıyorlar. Bildiğimiz kötü niyetli insanlar (hakerler) servere ulaşınca bilgi alabilir, mesajlarımızı okuyabilirler vs.
 Bizim projemizde server olmayan bir ağ oluşturmak isteriz. Böylece İnternet hiç kullanmadan birbirimizi haberleşebiliriz. Elimizde yeterki bilgisayar ve LoRa modülü olsun. Örnek olarak Bursa’da 10 tane LoRa kullanıcı olsa farklı ilçelerden yazışabilirler. Yeni kullanıcı geldiğinde aynı ağa girip mesajlaşabilir.
 Kullanıcıya sade ve kolayca kullanabileceği bir masaüstü uygulaması tasarlıyoruz. Bu uygulamayı kullanmak için müşterinin LoRa veya uygulamanın kendisi hakkında fazla bilgiye ihtiyacı olmayacak. LoRa modülünü bilgisayara taktıktan sonra uygulamayı çalıştırıp direkt kullanmaya başlayabilmesini sağlıyoruz. Kullanıcı, uygulamayı açtıktan sonra ayarlar ekranı ile karşılaşacaktır. Bu ekranda profil fotoğrafı ve kullanıcı adı belirlenebiliyor. Böylece müşteri, kiminle yazıştığını çok daha kolay bir şekilde anlayabilir. Mesajlar da en basit bildiğimiz yöntemle yazıp göndereceğiz. Ne kadar kullanışlı ve uygun olsa o kadar insan onu tercih edebilir. Ne kadar insan tercih ederse o kadar büyük ve sağlam bir ağ oluşturacağız.

**Comment by BlackHacherUU** [comment]
3 a KONU(Abdullah HASAN)
 Günümüzde Wİ-Fİ kullanmayan insan yoktur. Biz de server’e istek gönderip bilgiler alabiliriz. Bir server çöktüğünde istemciler (Clients) iletişim kuramıyor ve sıkıntı yaşıyor. Son günlerde sosyal medyada bazı uygulamalar bir süre çalışmaz haline geldiği için insanlar iletişim kuramıdalar. Böylece yeni uygulama indirip başka yol arıyorlar. Bildiğimiz kötü niyetli insanlar (hakerler) servere ulaşınca bilgi alabilir, mesajlarımızı okuyabilirler vs.
 Bizim projemizde server olmayan bir ağ oluşturmak isteriz. Böylece İnternet hiç kullanmadan birbirimizi haberleşebiliriz. Elimizde yeterki bilgisayar ve LoRa modülü olsun. Örnek olarak Bursa’da 10 tane LoRa kullanıcı olsa farklı ilçelerden yazışabilirler. Yeni kullanıcı geldiğinde aynı ağa girip mesajlaşabilir.
 Kullanıcıya sade ve kolayca kullanabileceği bir masaüstü uygulaması tasarlıyoruz. Bu uygulamayı kullanmak için müşterinin LoRa veya uygulamanın kendisi hakkında fazla bilgiye ihtiyacı olmayacak. LoRa modülünü bilgisayara taktıktan sonra uygulamayı çalıştırıp direkt kullanmaya başlayabilmesini sağlıyoruz. Kullanıcı, uygulamayı açtıktan sonra ayarlar ekranı ile karşılaşacaktır. Bu ekranda profil fotoğrafı ve kullanıcı adı belirlenebiliyor. Böylece müşteri, kiminle yazıştığını çok daha kolay bir şekilde anlayabilir. Mesajlar da en basit bildiğimiz yöntemle yazıp göndereceğiz. Ne kadar kullanışlı ve uygun olsa o kadar insan onu tercih edebilir. Ne kadar insan tercih ederse o kadar büyük ve sağlam bir ağ oluşturacağız.
